basePath: /
host: localhost:8080
info:
  contact:
    email: znss1989@gmail.com
    name: Lei Wu
  description: This is web server for channel news
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: MM News APIs
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
swagger: "2.0"
